/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package home.view;

import KTPM.exception.InvalidCmndException;
import KTPM.exception.InvalidDobException;
import KTPM.exception.InvalidNameException;
import KTPM.exception.InvalidPersonIdException;
import KTPM.exception.InvalidSdtException;
import KTPMfinal.model.Vaccine;
import com.sun.java.accessibility.util.AWTEventMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import KTPMfinal.model.Person;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class AddHoSoDialog extends javax.swing.JDialog implements ActionListener {

    private HomeFrm homeFrm;
    private List<Person> persons;

    /**
     * Creates new form AddVaccineDialog
     */
    public AddHoSoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        addActionListener();
        homeFrm = (HomeFrm) parent;
    }

    public AddHoSoDialog(java.awt.Frame parent, boolean modal, List<Person> persons) {
        this(parent, modal);
        this.persons = persons;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAddMaHS = new javax.swing.JTextField();
        txtAddDiaChiHS = new javax.swing.JTextField();
        txtAddSdtHS = new javax.swing.JTextField();
        txtAddDobHS = new javax.swing.JTextField();
        btnAddHS = new javax.swing.JButton();
        btnClearHS = new javax.swing.JButton();
        btnCancelHS = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtAddNameHS = new javax.swing.JTextField();
        txtAddCmndHS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THÊM MỚI HỒ SƠ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm mới Hồ Sơ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã hồ sơ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Họ và tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Địa chỉ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số điện thoại");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ngày sinh");

        btnAddHS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddHS.setText("Thêm mới");

        btnClearHS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClearHS.setText("Xóa dữ liệu");

        btnCancelHS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelHS.setText("Hủy bỏ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("CMND/CCCD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddHS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnClearHS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnCancelHS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddDobHS)
                            .addComponent(txtAddMaHS)
                            .addComponent(txtAddSdtHS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddDiaChiHS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddNameHS)
                            .addComponent(txtAddCmndHS))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddNameHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtAddDiaChiHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAddCmndHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAddSdtHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddDobHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddHS)
                    .addComponent(btnClearHS)
                    .addComponent(btnCancelHS))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddHoSoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddHoSoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddHoSoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddHoSoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddHoSoDialog dialog = new AddHoSoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHS;
    private javax.swing.JButton btnCancelHS;
    private javax.swing.JButton btnClearHS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddCmndHS;
    private javax.swing.JTextField txtAddDiaChiHS;
    private javax.swing.JTextField txtAddDobHS;
    private javax.swing.JTextField txtAddMaHS;
    private javax.swing.JTextField txtAddNameHS;
    private javax.swing.JTextField txtAddSdtHS;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        var obj = e.getSource();
        if (obj.equals(btnAddHS)) {
            ThemHoSo();
        } else if (obj.equals(btnCancelHS)) {
            dispose();
        } else if (obj.equals(btnClearHS)) {
            ClearInputData();
        }
    }
    
    private void addActionListener() {
        btnAddHS.addActionListener(this);
        btnCancelHS.addActionListener(this);
        btnClearHS.addActionListener(this);
    }
    
    private void ClearInputData() {
        var textEmpty = "";
        txtAddMaHS.setText(textEmpty);
        txtAddSdtHS.setText(textEmpty);
        txtAddNameHS.setText(textEmpty);
        txtAddDobHS.setText("dd/MM/yyyy");
        txtAddDiaChiHS.setText(textEmpty);
        txtAddCmndHS.setText(textEmpty);
    }
    
    private void ThemHoSo() {
        var id = txtAddMaHS.getText();
        var name = txtAddNameHS.getText();
        var dob = txtAddDobHS.getText();
        var address = txtAddDiaChiHS.getText();
        var cmnd = txtAddCmndHS.getText();
        var sdt = txtAddSdtHS.getText();
        if (id.isEmpty() || name.isEmpty() || dob.isEmpty()
                || address.isEmpty() || sdt.isEmpty()) {
            var msg = "Các ô nhập liệu trên không được để trống!";
            showMessage(msg);
        } else {
            try {
                Person person = new Person(id,name,address,cmnd,sdt,dob);
                if(persons.contains(person)){
                    var msg= "Hồ sơ "+ id + " đã tồn tại trong danh sách!";
                    showMessage(msg);
                }
                else{
                    homeFrm.AddPersonComeBack(person);
                    var msg="Thêm mới hồ sơ thành công!";
                    showMessage(msg);
                    dispose();
                }
            } catch (InvalidPersonIdException ex) {
                var msg= ".Mã hồ sơ phải có dạng: XXabcd, X là chữ cái, a là chữ số";
                showMessage(ex.getMessage() + msg);
            } catch (InvalidCmndException ex) {
                var msg= " .CMND/CCCD phải gồm từ [8-13] số";
                showMessage(ex.getMessage() + msg);
            } catch (InvalidDobException ex) {
               var msg= " .Năm sinh phải có dạng dd/MM/yyyy. Trong đó dd: ngày sinh; MM: tháng sinh";
                showMessage(ex.getMessage() + msg);
            } catch (InvalidSdtException ex) {
                var msg= " .SĐT phải gồm từ [9-10] số và không có chữ cái";
                showMessage(ex.getMessage() + msg);
            } catch (InvalidNameException ex) {
               var msg= " .Tên riêng không được có ký tự số!";
                showMessage(ex.getMessage() + msg);
            }
    }}
    
    private void showMessage(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
    }
}
