/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package home.view;

import KTPM.controller.InfoFilterImp;
import KTPM.exception.InvalidCmndException;
import KTPM.exception.InvalidDobException;
import KTPM.exception.InvalidNameException;
import KTPM.exception.InvalidPersonIdException;
import KTPM.exception.InvalidSdtException;
import KTPMfinal.model.ChiTietPhieuTiem;
import KTPMfinal.model.LoVaccine;
import KTPMfinal.model.Vaccine;
import com.sun.java.accessibility.util.AWTEventMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import KTPMfinal.model.Person;
import KTPMfinal.model.PhieuDangKyTiem;
import KTPMfinal.model.PhieuTiem;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class AddPhieuDangKyTiem extends javax.swing.JDialog implements ActionListener {

    private HomeFrm homeFrm;
    private List<Vaccine> vaccines;
    private Person person;
    private Vaccine vaccine;
    private List<Person> persons;
    private List<PhieuDangKyTiem> phieuDangKyTiems;
    private PhieuDangKyTiem phieuDangKyTiem;

    /**
     * Creates new form AddVaccineDialog
     */
    public AddPhieuDangKyTiem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        addActionListener();
        homeFrm = (HomeFrm) parent;
    }

    public AddPhieuDangKyTiem(java.awt.Frame parent, boolean modal, List<Vaccine> vaccines, 
            List<PhieuDangKyTiem> phieuDangKyTiemTiem,
            List<Person> persons) {
        this(parent, modal);
        this.vaccines = vaccines;
        this.phieuDangKyTiems = phieuDangKyTiemTiem;
        this.persons = persons;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCheckIdNguoiTiem = new javax.swing.JTextField();
        txtNameVC = new javax.swing.JTextField();
        txtNgayDkTiem = new javax.swing.JTextField();
        btnAddPDKT = new javax.swing.JButton();
        btnClearPT = new javax.swing.JButton();
        btnCancelPT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCheckIdVC = new javax.swing.JTextField();
        txtMaPhieuDkTiem = new javax.swing.JTextField();
        btnSearchNT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNameNguoiTiem = new javax.swing.JTextField();
        btnSearchVC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THÊM MỚI PHIẾU ĐĂNG KÝ TIÊM");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM MỚI PHIẾU ĐK TIÊM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã người tiêm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã  Vaccine");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên Vaccine");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Ngày đk tiêm");

        btnAddPDKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddPDKT.setText("Thêm mới");

        btnClearPT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClearPT.setText("Xóa dữ liệu");

        btnCancelPT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelPT.setText("Hủy bỏ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mã phiếu đk tiêm");

        btnSearchNT.setText("Tìm kiếm");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Họ và tên");

        btnSearchVC.setText("Kiểm tra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddPDKT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearPT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnCancelPT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayDkTiem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNameVC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaPhieuDkTiem)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCheckIdNguoiTiem, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchNT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNameNguoiTiem)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCheckIdVC, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnSearchVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCheckIdNguoiTiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchNT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNameNguoiTiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckIdVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnSearchVC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhieuDkTiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayDkTiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPDKT)
                    .addComponent(btnClearPT)
                    .addComponent(btnCancelPT))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPhieuDangKyTiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPhieuDangKyTiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPhieuDangKyTiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPhieuDangKyTiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddPhieuDangKyTiem dialog = new AddPhieuDangKyTiem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPDKT;
    private javax.swing.JButton btnCancelPT;
    private javax.swing.JButton btnClearPT;
    private javax.swing.JButton btnSearchNT;
    private javax.swing.JButton btnSearchVC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCheckIdNguoiTiem;
    private javax.swing.JTextField txtCheckIdVC;
    private javax.swing.JTextField txtMaPhieuDkTiem;
    private javax.swing.JTextField txtNameNguoiTiem;
    private javax.swing.JTextField txtNameVC;
    private javax.swing.JTextField txtNgayDkTiem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        var obj = e.getSource();
        if (obj.equals(btnAddPDKT)) {
            ThemPhieuTiem();
        } else if (obj.equals(btnCancelPT)) {
            dispose();
        } else if (obj.equals(btnClearPT)) {
            ClearInputData();
        } else if (obj.equals(btnSearchNT)) {
            TimIdPerson();
        } else if (obj.equals(btnSearchVC)) {
           TimIdLoVaccine();
        
  
        }
    }

    private void addActionListener() {
        btnAddPDKT.addActionListener(this);
        btnCancelPT.addActionListener(this);
        btnClearPT.addActionListener(this);
        btnSearchNT.addActionListener(this);
        btnSearchVC.addActionListener(this);
    }

    private void ClearInputData() {
        var textEmpty = "";
        txtCheckIdNguoiTiem.setText(textEmpty);
        txtNgayDkTiem.setText(textEmpty);
        txtCheckIdVC.setText(textEmpty);
        txtNameVC.setText(textEmpty);
        txtMaPhieuDkTiem.setText(textEmpty);
        txtNameNguoiTiem.setText(textEmpty);
    }

    private void ThemPhieuTiem() {
        if (vaccine == null) {
            var msg = "Vui lòng nhập  Vaccine cần tìm!";
            showMessage(msg);
        } else if (person == null) {
            var msg = "Vui lòng nhập Người Tiêm cần tìm!";
            showMessage(msg);
        } else {
            var ngayDkTiem = txtNgayDkTiem.getText();
            var maPhieudkTiem = txtMaPhieuDkTiem.getText();
            if (ngayDkTiem.isEmpty() || maPhieudkTiem.isEmpty()) {
                var msg = "Vui lòng nhập đầy đủ thông tin Phiếu Tiêm!";
                showMessage(msg);
            } else {
                try {
                    phieuDangKyTiem = new PhieuDangKyTiem(vaccine,person,ngayDkTiem,maPhieudkTiem);
                     var checker = new InfoFilterImp();
                    if (checker.isKiemTraPhieuDkTiem(phieuDangKyTiems, phieuDangKyTiem)){
                        var msg = "Phiếu đăng ký tiêm: " + maPhieudkTiem  + " đã tồn tại trong danh sách!";
                        showMessage(msg);
                    } else {
                        homeFrm.AddPhieuDkTiemComeBack(phieuDangKyTiem);
                        var msg = "Thêm mới 1 Phiếu đăng ký tiêm  thành công!";
                        showMessage(msg);
                        dispose();
                    }
                } catch (InvalidDobException ex) {
                     var msg = " .Định dạng thời gian phải ở dạng dd/MM/yyyy. Trong đó dd: ngày sinh; MM: tháng sinh";
                    showMessage(ex.getMessage() + msg);
                }
            }
        }
    }

    private void showMessage(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
    }

    private void TimIdPerson() {
        person = null;
        var personId = txtCheckIdNguoiTiem.getText().trim();
        if (personId.isEmpty()) {
            var msg = "Vui lòng nhập mã Người Tiêm cần tìm";
            showMessage(msg);
        } else {
            for (Person p : persons) {
                if (p.getId().compareTo(personId) == 0) {
                    person = p;
                    break;
                }
            }
            if (person == null) {
                var msg = "Người này không tồn tại trong danh sách hồ sơ người tiêm. Mời thêm mới Hồ sơ người tiêm!";
                showMessage(msg);
                txtCheckIdNguoiTiem.setText("");
                txtNameNguoiTiem.setText("");
            } else {
                txtNameNguoiTiem.setText(person.getFullname());
            }
        }

    }

    private void TimIdLoVaccine() {
        vaccine=null;
        var vaccineId = txtCheckIdVC.getText().trim();
        if (vaccineId.isEmpty()) {
            var msg = "Vui lòng nhập mã  Vaccine cần tìm";
            showMessage(msg);
        } else {
            for (Vaccine vaccine: vaccines) {
                if(vaccine.getId() == Integer.parseInt(vaccineId)){
                    this.vaccine = vaccine;
                    break;
                    
            }
            }
            
            if (vaccine == null) {
                var msg = "Loại Vaccine này không nằm trong trạm y tế. Xin hãy kiểm tra lại!";
                showMessage(msg);
                txtCheckIdVC.setText("");
                txtNameVC.setText("");

            } else {
                   
                   
                        txtNameVC.setText(vaccine.getName());  
                    
                          
            }

        }
    }
}
